# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import primalitytest_pb2 as primalitytest__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in primalitytest_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Heartbeat = channel.unary_unary(
                '/prime.ControlService/Heartbeat',
                request_serializer=primalitytest__pb2.Empty.SerializeToString,
                response_deserializer=primalitytest__pb2.Ack.FromString,
                _registered_method=True)
        self.SnapshotMarker = channel.unary_unary(
                '/prime.ControlService/SnapshotMarker',
                request_serializer=primalitytest__pb2.SnapshotMarkerReq.SerializeToString,
                response_deserializer=primalitytest__pb2.Ack.FromString,
                _registered_method=True)
        self.SnapshotCollect = channel.unary_unary(
                '/prime.ControlService/SnapshotCollect',
                request_serializer=primalitytest__pb2.SnapshotCollectReq.SerializeToString,
                response_deserializer=primalitytest__pb2.SnapshotBlob.FromString,
                _registered_method=True)
        self.Restore = channel.unary_unary(
                '/prime.ControlService/Restore',
                request_serializer=primalitytest__pb2.RestoreReq.SerializeToString,
                response_deserializer=primalitytest__pb2.Ack.FromString,
                _registered_method=True)


class ControlServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SnapshotMarker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SnapshotCollect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Restore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=primalitytest__pb2.Empty.FromString,
                    response_serializer=primalitytest__pb2.Ack.SerializeToString,
            ),
            'SnapshotMarker': grpc.unary_unary_rpc_method_handler(
                    servicer.SnapshotMarker,
                    request_deserializer=primalitytest__pb2.SnapshotMarkerReq.FromString,
                    response_serializer=primalitytest__pb2.Ack.SerializeToString,
            ),
            'SnapshotCollect': grpc.unary_unary_rpc_method_handler(
                    servicer.SnapshotCollect,
                    request_deserializer=primalitytest__pb2.SnapshotCollectReq.FromString,
                    response_serializer=primalitytest__pb2.SnapshotBlob.SerializeToString,
            ),
            'Restore': grpc.unary_unary_rpc_method_handler(
                    servicer.Restore,
                    request_deserializer=primalitytest__pb2.RestoreReq.FromString,
                    response_serializer=primalitytest__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'prime.ControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('prime.ControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prime.ControlService/Heartbeat',
            primalitytest__pb2.Empty.SerializeToString,
            primalitytest__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SnapshotMarker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prime.ControlService/SnapshotMarker',
            primalitytest__pb2.SnapshotMarkerReq.SerializeToString,
            primalitytest__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SnapshotCollect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prime.ControlService/SnapshotCollect',
            primalitytest__pb2.SnapshotCollectReq.SerializeToString,
            primalitytest__pb2.SnapshotBlob.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Restore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prime.ControlService/Restore',
            primalitytest__pb2.RestoreReq.SerializeToString,
            primalitytest__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CoordinatorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AssignChunk = channel.unary_unary(
                '/prime.CoordinatorService/AssignChunk',
                request_serializer=primalitytest__pb2.Chunk.SerializeToString,
                response_deserializer=primalitytest__pb2.Ack.FromString,
                _registered_method=True)


class CoordinatorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AssignChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AssignChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignChunk,
                    request_deserializer=primalitytest__pb2.Chunk.FromString,
                    response_serializer=primalitytest__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'prime.CoordinatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('prime.CoordinatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoordinatorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AssignChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prime.CoordinatorService/AssignChunk',
            primalitytest__pb2.Chunk.SerializeToString,
            primalitytest__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ShardServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EmitPrime = channel.unary_unary(
                '/prime.ShardService/EmitPrime',
                request_serializer=primalitytest__pb2.PrimeMsg.SerializeToString,
                response_deserializer=primalitytest__pb2.Ack.FromString,
                _registered_method=True)


class ShardServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EmitPrime(self, request, context):
        """A worker calls EmitPrime on the *owner* worker (shard)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShardServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EmitPrime': grpc.unary_unary_rpc_method_handler(
                    servicer.EmitPrime,
                    request_deserializer=primalitytest__pb2.PrimeMsg.FromString,
                    response_serializer=primalitytest__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'prime.ShardService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('prime.ShardService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShardService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EmitPrime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prime.ShardService/EmitPrime',
            primalitytest__pb2.PrimeMsg.SerializeToString,
            primalitytest__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
