# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: primalitytest.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'primalitytest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13primalitytest.proto\x12\x05prime\"\x07\n\x05\x45mpty\"\x1e\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\"1\n\x05\x43hunk\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t\x12\r\n\x05start\x18\x02 \x01(\x03\x12\x0b\n\x03\x65nd\x18\x03 \x01(\x03\"<\n\x08PrimeMsg\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x0e\n\x06msg_id\x18\x02 \x01(\t\x12\r\n\x05prime\x18\x03 \x01(\x04\";\n\x11SnapshotMarkerReq\x12\x13\n\x0bsnapshot_id\x18\x01 \x01(\t\x12\x11\n\tfrom_node\x18\x02 \x01(\t\")\n\x12SnapshotCollectReq\x12\x13\n\x0bsnapshot_id\x18\x01 \x01(\t\"H\n\x0cSnapshotBlob\x12\x13\n\x0bsnapshot_id\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\x12\n\njson_state\x18\x03 \x01(\t\"!\n\nRestoreReq\x12\x13\n\x0bsnapshot_id\x18\x01 \x01(\t2\xe4\x01\n\x0e\x43ontrolService\x12\'\n\tHeartbeat\x12\x0c.prime.Empty\x1a\n.prime.Ack\"\x00\x12\x38\n\x0eSnapshotMarker\x12\x18.prime.SnapshotMarkerReq\x1a\n.prime.Ack\"\x00\x12\x43\n\x0fSnapshotCollect\x12\x19.prime.SnapshotCollectReq\x1a\x13.prime.SnapshotBlob\"\x00\x12*\n\x07Restore\x12\x11.prime.RestoreReq\x1a\n.prime.Ack\"\x00\x32?\n\x12\x43oordinatorService\x12)\n\x0b\x41ssignChunk\x12\x0c.prime.Chunk\x1a\n.prime.Ack\"\x00\x32:\n\x0cShardService\x12*\n\tEmitPrime\x12\x0f.prime.PrimeMsg\x1a\n.prime.Ack\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'primalitytest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=30
  _globals['_EMPTY']._serialized_end=37
  _globals['_ACK']._serialized_start=39
  _globals['_ACK']._serialized_end=69
  _globals['_CHUNK']._serialized_start=71
  _globals['_CHUNK']._serialized_end=120
  _globals['_PRIMEMSG']._serialized_start=122
  _globals['_PRIMEMSG']._serialized_end=182
  _globals['_SNAPSHOTMARKERREQ']._serialized_start=184
  _globals['_SNAPSHOTMARKERREQ']._serialized_end=243
  _globals['_SNAPSHOTCOLLECTREQ']._serialized_start=245
  _globals['_SNAPSHOTCOLLECTREQ']._serialized_end=286
  _globals['_SNAPSHOTBLOB']._serialized_start=288
  _globals['_SNAPSHOTBLOB']._serialized_end=360
  _globals['_RESTOREREQ']._serialized_start=362
  _globals['_RESTOREREQ']._serialized_end=395
  _globals['_CONTROLSERVICE']._serialized_start=398
  _globals['_CONTROLSERVICE']._serialized_end=626
  _globals['_COORDINATORSERVICE']._serialized_start=628
  _globals['_COORDINATORSERVICE']._serialized_end=691
  _globals['_SHARDSERVICE']._serialized_start=693
  _globals['_SHARDSERVICE']._serialized_end=751
# @@protoc_insertion_point(module_scope)
